print(123)     #this is a single word quote string
print ("Python Session 1")  #sentence in a double-quote string

#use of variables with strings

fruits = "Apple, Orange, Banana" #create the variables, store the value and then print, in this example fruits is the variable
print (fruits)

#input functions. all functions of python has specific task to do
#input function is to take task specifically from the user and execute with inbuilt capability
#using the input function

myname = input ("Please enter your name\n")
print ("Hi ", myname, "Welcome to your first Python Lab Session")
