#Strings

#ceit = "CCDBM"
#print (ceit)
#print (1234) 

#add # infront of the command to avoid repetitive output
#u can use variable in python just like the ceit
#strings need quotes whereas numbers dont need quotes
#we use the type() function to determine the datatype of an object in python
#a variable will always be infront of the equal sign
#variable will never bee in double quotes

#myname = input("Please enter your name\n")
#print("Hi ", myname, "Welcome to CEIT")

#Using type function
#print (type(ceit))

#functions after the dot. is now a method its trying 

#Len function
#print(len(ceit))

#Practice exercise Q1
x =  "hello"
print(x)

#Q2
print(x(0))
print(x(1))

#Q3

